### ISSUE TITLE
In node v10.0, build failed

### ISSUE THREAD

**Issue by dotneet** [bcoin-org/bcoin-native#5]
Hi, is there way to avoid this problem?

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/bcoin-native/src/poly1305-donna/poly1305-donna.o
  CC(target) Release/obj.target/bcoin-native/src/chacha20-simple/chacha20_simple.o
  CC(target) Release/obj.target/bcoin-native/src/scrypt/insecure_memzero.o
  CC(target) Release/obj.target/bcoin-native/src/scrypt/sha256.o
  CC(target) Release/obj.target/bcoin-native/src/scrypt/crypto_scrypt.o
  CXX(target) Release/obj.target/bcoin-native/src/chacha20.o
  CXX(target) Release/obj.target/bcoin-native/src/poly1305.o
  CXX(target) Release/obj.target/bcoin-native/src/digest.o
../src/digest.cc:28:14: error: variable has incomplete type 'EVP_MD_CTX' (aka 'evp_md_ctx_st')
  EVP_MD_CTX mdctx;
             ^
/Users/xxxx/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:92:16: note: forward declaration of 'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
../src/digest.cc:58:12: error: variable has incomplete type 'HMAC_CTX' (aka 'hmac_ctx_st')
  HMAC_CTX hmctx;
           ^
/Users/xxxx/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:102:16: note: forward declaration of 'hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
2 errors generated.
make: *** [Release/obj.target/bcoin-native/src/digest.o] Error 1
```

**Comment by rolme** [comment]
I am getting the same error as well:
```
» npm install -g bcoin-native@0.0.23

> bcoin-native@0.0.23 install /usr/local/lib/node_modules/bcoin-native
> node-gyp rebuild

  CC(target) Release/obj.target/bcoin-native/src/poly1305-donna/poly1305-donna.o
  CC(target) Release/obj.target/bcoin-native/src/chacha20-simple/chacha20_simple.o
  CC(target) Release/obj.target/bcoin-native/src/scrypt/insecure_memzero.o
  CC(target) Release/obj.target/bcoin-native/src/scrypt/sha256.o
  CC(target) Release/obj.target/bcoin-native/src/scrypt/crypto_scrypt.o
  CXX(target) Release/obj.target/bcoin-native/src/chacha20.o
  CXX(target) Release/obj.target/bcoin-native/src/poly1305.o
  CXX(target) Release/obj.target/bcoin-native/src/digest.o
../src/digest.cc:28:14: error: variable has incomplete type 'EVP_MD_CTX'
      (aka 'evp_md_ctx_st')
  EVP_MD_CTX mdctx;
             ^
/Users/rparnaso/.node-gyp/10.3.0/include/node/openssl/ossl_typ.h:92:16: note: forward
      declaration of 'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
../src/digest.cc:58:12: error: variable has incomplete type 'HMAC_CTX'
      (aka 'hmac_ctx_st')
  HMAC_CTX hmctx;
           ^
/Users/rparnaso/.node-gyp/10.3.0/include/node/openssl/ossl_typ.h:102:16: note: forward
      declaration of 'hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
2 errors generated.
make: *** [Release/obj.target/bcoin-native/src/digest.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bcoin-native
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by rolme** [comment]
After downgrading to node@9.11.1, it properly compiled.

**Comment by bogdyak** [comment]
Is there any solution without downgrading node version. 
I am using `12.15.0`

**Comment by pinheadmz** [comment]
@bogdyak this repo is deprecated. What are you trying to do?
